### ISSUE TITLE
Plugin doesn't include image assets in folder, 404 error for ui and background files

### ISSUE THREAD

**Issue by mtvaccaro** [auxdesigner/Sketch-to-VR#5]
The plugin creates a folder that only contains the HTML file. When I launch the HTTP Simple Server, all I see is a black screen with the VR cursor in the center (404 errors in console that image files can't be found). I then manually export the two artboards to the directory, but it still can't find them when I run the server again. Help!

**Comment by auxdesigner** [comment]
This appears to be an issue with the latest version of Sketch. I'll look into it.

**Comment by auxdesigner** [comment]
Found this from the Sketch Dev thread:

Hi everyone,

we're getting ready for a beta release of Sketch 41, and wanted to let you know about some changes that might be breaking some plugins out there.

Basically, MSExportRequest.requestWithRect_scale_ was removed in a recent refactor to make the code a bit cleaner.

So now, instead of

request = MSExportRequest.requestWithRect_scale_(rect, scale)
you need to do:

request = MSExportRequest.new()
request.rect = rect
request.scale = scale
This should work fine in Sketch 40.3, so you can implement the change ahead of the official release and don't disrupt your customers' workflow.

Sorry about the troubles, and have a nice Wednesday!

I'll make the updates.

**Comment by auxdesigner** [comment]
This is fixed in the latest update
https://github.com/auxdesigner/Sketch-to-VR/commit/bf5be607de620c34537a4cbe328bbe8f08964639

**Comment by mtvaccaro** [comment]
Since the latest Sketch update I have still not been able to use this plugin. I have reinstalled the plugin, it continues to only export the .html file to the demo.sketch-vr directory. Launching the server from that directory displays only a black screen and 404 errors for the artboards that are not present in the directory. If I export them to the directory, I still receive the errors.
EDIT: Ah, found the problem. It was searching for those .pngs in a subdirectory titled /img. Once I created that directory and put the files in there, it rendered properly.. Strange though, in the past that /img directory was created automatically during the export-- something change there?

**Comment by NETWORK101** [comment]
Please remove me

**Comment by auxdesigner** [comment]
@mtvaccaro  What's your Sketch version? Thanks!

**Comment by mtvaccaro** [comment]
41.2

I think the problem is that I had installed the new plugin, but I had two instances of the plugin in my dropdown (one current, one legacy). I was using the legacy plugin with the new Sketch version, and it wasn't creating that subdirectory. However the the current plugin does seem to create it properly. My apologies for the confusion. And thanks for an excellent sketch plugin!

**Comment by auxdesigner** [comment]
@mtvaccaro Thanks! Glad it worked!
